# Change these first
owner: svbmuc # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: 'S端dtiroler Volksb端hne'
    url: https://www.suedtiroler-volksbuehne.de

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Systemstatus von S端dtiroler Volksb端hne
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

